language: php
matrix:
  include:
    - php: 5.3
      env: PUG_VERSION='^2.7'
      dist: precise
      sudo: required
    - php: 5.4
      env: PUG_VERSION='^2.7'
    - php: 5.5
      env: PUG_VERSION='^2.7'
    - php: 5.5
      env: PUG_VERSION='^3.0'
    - php: 5.6
      env: PUG_VERSION='^2.7'
    - php: 5.6
      env: PUG_VERSION='^3.0'
    - php: 7.0
      env: PUG_VERSION='^2.7'
    - php: 7.0
      env: PUG_VERSION='^3.0'
    - php: 7.1
      env: PUG_VERSION='^2.7'
    - php: 7.1
      env: PUG_VERSION='^3.0'
    - php: 7.2
      env: PUG_VERSION='^2.7'
    - php: 7.2
      env: PUG_VERSION='^3.0'
    - php: 7.3
      env: PUG_VERSION='^2.7'
    - php: 7.3
      env: PUG_VERSION='^3.0'
    - php: hhvm
      env: PUG_VERSION='^2.7'
      dist: trusty
      sudo: required
    - php: hhvm
      env: PUG_VERSION='^3.0'
      dist: trusty
      sudo: required
before_script:
  - travis_retry composer self-update
  - if [ "$PUG_VERSION" != "" ]; then travis_retry composer require "pug-php/pug:${PUG_VERSION}" --no-update; fi;
  - travis_retry composer update --no-interaction
script:
  - vendor/bin/phpunit --verbose --coverage-text --coverage-clover=coverage.xml
after_script:
  - vendor/bin/test-reporter --coverage-report coverage.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
addons:
  code_climate:
    repo_token: 2c5c4708df9d12fcba852dd790c57e53b7f87280f528cbbc0dc6413d13841d76
